name = "workers-airtable-form"
type = "javascript"

account_id = "7a87cf4fc7e9382f6461c3c09d98f539"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appuc1ZxHxLnY0E0P"
AIRTABLE_TABLE_NAME = "DemoBase"
FORM_URL = "https://airtable.com/shr0RQQW5nOaHXs5j"
