name = "workers-airtable-form"
type = "javascript"

account_id = "be35ea6bd4f0812a33b1698be995715d"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appsHlYcAkzVhzmYl"
AIRTABLE_TABLE_NAME = "Form Submissions"
FORM_URL = "https://workers-airtable-form.pages.dev"
